apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  type: NodePort
  ports:
    - name: cql
      port: 9042
      nodePort: 30000
    - name: mx4j
      port: 8081
      nodePort: 30001
  selector:
    app: cassandra

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: cassandra
  name: cassandra
spec:
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: merapar/cassandra:1.0
          name: cassandra
          volumeMounts:
            - mountPath: /cassandra-storage
              name: cassandra-storage
      volumes:
        - name: cassandra-storage
          hostPath:
            path: /cassandra-storage
