apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  clusterIP: None
  ports:
    - name: cql
      port: 9042
  selector:
    app: cassandra

---

apiVersion: v1
kind: Service
metadata:
  name: cassandra-external
spec:
  type: NodePort
  ports:
    - name: cql
      port: 9042
      nodePort: 30000
  selector:
    app: cassandra
